### ISSUE TITLE
get coveralls for python up

### ISSUE THREAD

**Issue by aew61** [cwrucutter/Classifiers#2]
coveralls is different for every language. We have a process for C/C++, but not for Python. Check out https://github.com/coagulant/coveralls-python for Python coverage

**Comment by kleinma** [comment]
How's this coming along?

**Comment by aew61** [comment]
I'm reading about how rospy and catkin play together so I can get test code building so I can then do coverage. I think everything's set up, I just have to start using it.

**Comment by aew61** [comment]
trying to use python nosetest's coverage.py file. Earlier tonight catkin started building the pyclassifiers package (although I hadn't really changed anything) so I can start getting coverage up. Unfortunately, running the default version of coverage.py isn't really helpful (it covers ALL imported code) so manually playing with it should help.
